### ISSUE TITLE
ViewBinding

### ISSUE THREAD

**Issue by EmogurovAnton** [Sirenser/DotaStatApplication#1]
Не очень хорошая практика использовать биндинг с lateinit `private lateinit var binding: AuthorizationFragmentBinding`, т.к могут возникать утечки памяти, можно поискать в интернетах делегат специально для этого дела
У AndroidBroadcast есть самописный делегат в виде либы

**Comment by Sirenser** [comment]
Пофиксил в данном обновлении обьявление биндинга:
 `private var binding: AuthorizationFragmentBinding? = null`
